name: Development Build

on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ development ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.301
    - name: Install dependencies
      run: dotnet restore src/MongoDB.Context.sln
    - name: Build
      run: dotnet build src/MongoDB.Context.sln --configuration Release --no-restore
    - name: Test
      run: dotnet test src/MongoDB.Context.sln --no-restore --verbosity normal
