name: Master Build / Package Deploy

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.301

    - name: Install dependencies
      run: dotnet restore src/MongoDB.Context.sln

    - name: Build
      run: dotnet build src/MongoDB.Context.sln --configuration Release --no-restore

    - name: Test
      run: dotnet test src/MongoDB.Context.sln --no-restore --verbosity normal

    - name: Publish NuGet
      uses: rohith/publish-nuget@v2.2.1
      with:
        PROJECT_FILE_PATH: src/MongoDB.Context/MongoDB.Context.csproj
        TAG_COMMIT: true
        NUGET_KEY: ${{secrets.NUGET_KEY}}
